spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5432/software_devs
spring.datasource.username=test_user
spring.datasource.password=pass1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

jwt.secret=xT9$mK2@vL7#pQ4*zW8%yR1^cN5&bF0!ZxT9$mK2@vL7#pQ4*zW8%yR1^cN5&bF0!Z
management.endpoints.jmx.exposure.exclude=*

spring.security.oauth2.client.registration.google.client-id=22530824433-5tsgn4t2c13qiqk6tif72qipqg8dl5hb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
# 1. Registration Details with Microsoft
spring.security.oauth2.client.registration.microsoft.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.microsoft.client-secret=YOUR_CLIENT_SECRET
spring.security.oauth2.client.registration.microsoft.scope=openid, profile, email, offline_access
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.microsoft.redirect-uri={baseUrl}/login/oauth2/code/microsoft

# 2. Provider Details (Crucial for Microsoft)
spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.jwk-set-uri=https://login.microsoftonline.com/common/discovery/v2.0/keys
spring.security.oauth2.client.provider.microsoft.user-name-attribute=preferred_username