spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5432/software_devs
spring.datasource.username=test_user
spring.datasource.password=pass1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

jwt.secret=xT9$mK2@vL7#pQ4*zW8%yR1^cN5&bF0!ZxT9$mK2@vL7#pQ4*zW8%yR1^cN5&bF0!Z
management.endpoints.jmx.exposure.exclude=*

spring.security.oauth2.client.registration.google.client-id=22530824433-v794bc1q5mlw63yd2u2cn0hs6jnzf2gljhr486u3dkgm2y.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
